evo_config:
  _target_: shinka.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
  patch_type_probs:
    - 0.5
    - 0.5
  num_generations: 20
  max_parallel_jobs: 1
  max_patch_attempts: 10
  llm_models:
    - "gemini-flash-latest"
  llm_dynamic_selection: null
  embedding_model: "gemini-embedding-001"
  results_dir: ${output_dir}


