#!/usr/bin/env python3
import argparse

from shinka.core import EvolutionConfig, ShinkaEvolveRunner
from shinka.database import DatabaseConfig
from shinka.launch import LocalJobConfig


TASK_SYS_MSG = """
You are an expert mathematician with a specialization in group theory. You want
to prove the following statement:

"Let H be the subgroup generated by two elements a, b of a group G. Prove that
if a b = b a, then H is an abelian group."

Your task is to identify the minimal set of variables and assumptions needed to
formalize the proof in Lean 4. You do not have to provide the proof itself.

Output shape:

```lean
-- Variables
theorem abelian_group (<Write the variables needed for the proof here>)
-- Assumptions
<Write the assumptions needed to complete the proof here>
:
-- Conjecture
(<Write the proof's conjecture here>)
:=
```

Make sure your output is valid Lean 4. Do not leave the conjecture empty `()`.
Do not finish the proof.
""".strip()


def main(prover_model: str, results_dir: str, lean_timeout: int) -> None:
    job_config = LocalJobConfig(
        eval_program_path="evaluate.py",
        time="00:20:00",
        extra_cmd_args={
            "prover_model": prover_model,
            "lean_timeout": lean_timeout,
        },
    )

    db_config = DatabaseConfig(
        db_path="evolution_db.sqlite",
        num_islands=1,
        archive_size=20,
        elite_selection_ratio=0.3,
        num_archive_inspirations=1,
        num_top_k_inspirations=1,
    )

    evo_config = EvolutionConfig(
        task_sys_msg=TASK_SYS_MSG,
        patch_types=["diff", "full"],
        patch_type_probs=[0.7, 0.3],
        num_generations=12,
        max_patch_resamples=2,
        max_patch_attempts=3,
        job_type="local",
        language="lean",
        llm_models=["gpt-5-mini"],
        llm_kwargs={
            "temperatures": [0.2, 0.6, 0.9],
            "reasoning_efforts": ["medium"],
            "max_tokens": 16384,
        },
        embedding_model="text-embedding-3-small",
        code_embed_sim_threshold=0.995,
        init_program_path="initial.lean",
        results_dir=results_dir,
        max_novelty_attempts=1,
    )

    runner = ShinkaEvolveRunner(
        evo_config=evo_config,
        job_config=job_config,
        db_config=db_config,
        max_evaluation_jobs=1,
        max_proposal_jobs=1,
        max_db_workers=1,
        verbose=True,
    )
    runner.run()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--prover_model", type=str, default="gpt-5-nano")
    parser.add_argument("--lean_timeout", type=int, default=300)
    parser.add_argument(
        "--results_dir",
        type=str,
        default="results_autoformalization_small",
    )
    args = parser.parse_args()
    main(args.prover_model, args.results_dir, args.lean_timeout)
