repos:
  - repo: local
    hooks:
      - id: check-pinned-dependencies
        name: Check that all dependencies are pinned
        entry: python scripts/check_pinned_deps.py
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3.12
        args: ['--max-line-length=120', '--extend-ignore=E203,W503']

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles with hadolint
        language: docker_image
        types: ["dockerfile"]
        entry: hadolint/hadolint:v2.12.0 hadolint
