defaults:
  - override /database@_global_: island_medium
  - override /evolution@_global_: medium_budget
  - override /task@_global_: novelty_generator
  - override /cluster@_global_: local
  - _self_

variant_suffix: "_example"

evo_config:
  llm_models:
    - "gemini-2.5-flash"
  embedding_model: "gemini-embedding-001"